[package]
name = "rust_code_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full", "visit"] }
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
