/*
 * Copyright (c) 2009-2011, Salvatore Sanfilippo <antirez at gmail dot com>
 * Copyright (c) 2010-2011, Pieter Noordhuis <pcnoordhuis at gmail dot com>
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of Redis nor the names of its contributors may be used
 *     to endorse or promote products derived from this software without
 *     specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

use std::collections::HashMap;
use std::ffi::{CStr, CString};
use std::mem;
use std::os::raw::{c_char, c_int, c_void};
use std::ptr;
use std::time::Duration;

use libc::{self, sockaddr, timeval};

use crate::hiredis::{
    redisContext, redisFree, redisReply, redisReader, redisReaderFree, redisReaderGetReply,
    redisReaderCreate, redisReaderFeed, redisReaderGetError, redisReaderSetReplyObjectFunctions,
    redisReaderSetPrivdata, redisReaderSetProtocol, redisReaderSetReplyObjectFunctionsFree,
    redisReaderSetReplyObjectFunctionsMalloc, redisReaderSetReplyObjectFunctionsRealloc,
    redisReaderSetReplyObjectFunctionsStrdup, redisReaderSetReplyObjectFunctionsFreeObject,
    redisReaderSetReplyObjectFunctionsCreateString, redisReaderSetReplyObjectFunctionsCreateArray,
    redisReaderSetReplyObjectFunctionsCreateInteger, redisReaderSetReplyObjectFunctionsCreateNil,
    redisReaderSetReplyObjectFunctionsCreateStatus, redisReaderSetReplyObjectFunctionsCreateError,
    redisReaderSetReplyObjectFunctionsCreateDouble, redisReaderSetReplyObjectFunctionsCreateBool,
    redisReaderSetReplyObjectFunctionsCreateVerbatim, redisReaderSetReplyObjectFunctionsCreateMap,
    redisReaderSetReplyObjectFunctionsCreateSet, redisReaderSetReplyObjectFunctionsCreateAttribute,
    redisReaderSetReplyObjectFunctionsCreatePush, redisReaderSetReplyObjectFunctionsCreateBigNumber,
    redisReaderSetReplyObjectFunctionsCreateUnknown, redisReaderSetReplyObjectFunctionsCreateNull,
    redisReaderSetReplyObjectFunctionsCreateNone, redisReaderSetReplyObjectFunctionsCreateStreamID,
    redisReaderSetReplyObjectFunctionsCreateStreamItem, redisReaderSetReplyObjectFunctionsCreateStream,
    redisReaderSetReplyObjectFunctionsCreateStreamConsumer, redisReaderSetReplyObjectFunctionsCreateStreamConsumerGroup,
    redisReaderSetReplyObjectFunctionsCreateStreamPending, redisReaderSetReplyObjectFunctionsCreateStreamPendingReply,
    redisReaderSetReplyObjectFunctionsCreateStreamPendingMessage, redisReaderSetReplyObjectFunctionsCreateStreamPendingMessages,
    redisReaderSetReplyObjectFunctionsCreateStreamInfo, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroup,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumer, redisReaderSetReplyObjectFunctionsCreateStreamInfoPending,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroups, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumers,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessages, redisReaderSetReplyObjectFunctionsCreateStreamInfoReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumerReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoPendingReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupsReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoConsumersReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoMessagesReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply, redisReaderSetReplyObjectFunctionsCreateStreamInfoReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply,
    redisReaderSetReplyObjectFunctionsCreateStreamInfoGroupReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReplyReply