/* Autogenerated by build_info.pl - DO NOT EDIT */

/* This stores global variables that are initialized with
   preprocessor declarations for output with the --version flag.

   Copyright (C) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
   2004, 2005, 2006, 2007, 2008, 2009 Free Software Foundation, Inc.  */

use lazy_static::lazy_static;

lazy_static! {
    pub static ref COMPILED_FEATURES: Vec<&'static str> = {
        let mut features = Vec::new();

        #[cfg(feature = "cares")]
        features.push("+cares");
        #[cfg(not(feature = "cares"))]
        features.push("-cares");

        #[cfg(feature = "digest")]
        features.push("+digest");
        #[cfg(not(feature = "digest"))]
        features.push("-digest");

        #[cfg(feature = "gpgme")]
        features.push("+gpgme");
        #[cfg(not(feature = "gpgme"))]
        features.push("-gpgme");

        #[cfg(feature = "https")]
        features.push("+https");
        #[cfg(not(feature = "https"))]
        features.push("-https");

        #[cfg(feature = "ipv6")]
        features.push("+ipv6");
        #[cfg(not(feature = "ipv6"))]
        features.push("-ipv6");

        #[cfg(feature = "iri")]
        features.push("+iri");
        #[cfg(not(feature = "iri"))]
        features.push("-iri");

        #[cfg(any(target_pointer_width = "64", windows))]
        features.push("+large-file");
        #[cfg(not(any(target_pointer_width = "64", windows)))]
        features.push("-large-file");

        #[cfg(feature = "metalink")]
        features.push("+metalink");
        #[cfg(not(feature = "metalink"))]
        features.push("-metalink");

        #[cfg(feature = "nls")]
        features.push("+nls");
        #[cfg(not(feature = "nls"))]
        features.push("-nls");

        #[cfg(feature = "ntlm")]
        features.push("+ntlm");
        #[cfg(not(feature = "ntlm"))]
        features.push("-ntlm");

        #[cfg(feature = "opie")]
        features.push("+opie");
        #[cfg(not(feature = "opie"))]
        features.push("-opie");

        #[cfg(feature = "psl")]
        features.push("+psl");
        #[cfg(not(feature = "psl"))]
        features.push("-psl");

        #[cfg(any(feature = "openssl", feature = "openssl32"))]
        features.push("+ssl/openssl");
        #[cfg(feature = "gnutls")]
        features.push("+ssl/gnutls");
        #[cfg(not(any(feature = "openssl", feature = "openssl32", feature = "gnutls")))]
        features.push("-ssl");

        features
    };
}