/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
/* Casing Properties of Unicode characters. */
/* Generated automatically by gen-uni-tables.c for Unicode 15.0.0. */

/* Copyright (C) 2000-2022 Free Software Foundation, Inc.

   This file is free software.
   It is dual-licensed under "the GNU LGPLv3+ or the GNU GPLv2+".
   You can redistribute it and/or modify it under either
     - the terms of the GNU Lesser General Public License as published
       by the Free Software Foundation, either version 3, or (at your
       option) any later version, or
     - the terms of the GNU General Public License as published by the
       Free Software Foundation; either version 2, or (at your option)
       any later version, or
     - the same dual license "the GNU LGPLv3+ or the GNU GPLv2+".

   This file is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License and the GNU General Public License
   for more details.

   You should have received a copy of the GNU Lesser General Public
   License and of the GNU General Public License along with this
   program.  If not, see <https://www.gnu.org/licenses/>. */

const HEADER_0: usize = 16;
const HEADER_2: usize = 9;
const HEADER_3: usize = 127;
const HEADER_4: usize = 15;

static U_CASING_PROPERTY_CASE_IGNORABLE: CasingProperty = CasingProperty {
    header: [15],
    level1: [
        16 * std::mem::size_of::<i32>() / std::mem::size_of::<i16>() + 0,
        16 * std::mem::size_of::<i32>() / std::mem::size_of::<i16>() + 128,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 * std::mem::size_of::<i32>() / std::mem::size_of::<i16>() + 256,
    ],
    level2: [
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 0,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 16,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 32,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 48,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 64,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 80,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 96,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 112,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 128,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 144,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 160,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 176,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 192,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 208,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 224,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 240,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 256,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 272,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 288,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 304,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 320,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 336,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 352,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 368,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 384,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 400,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 416,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 432,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 448,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 464,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 480,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 496,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 512,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 528,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 544,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 560,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 576,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 592,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 608,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 624,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 640,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 656,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 672,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 688,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 704,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 720,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 736,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 752,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 768,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 784,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 800,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 816,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 832,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 848,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        16 + 384 * std::mem::size_of::<i16>() / std::mem::size_of::<i32>() + 864,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
