/* parser.rs -- convert the command line args into an expression tree.
   Copyright (C) 1990-2022 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

use std::ffi::{CStr, CString};
use std::os::unix::ffi::OsStrExt;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};
use std::fs::{File, Metadata};
use std::io::{self, Write};
use std::os::unix::fs::MetadataExt;
use std::collections::HashMap;
use std::env;
use std::process;
use std::str;
use std::sync::Arc;
use std::time::Duration;
use nix::sys::stat::{self, FileStat};
use nix::unistd;
use libc::{self, c_char, c_int, c_void, size_t};
use regex::Regex;
use glob::Pattern;
use chrono::{DateTime, Local};
use std::os::unix::fs::PermissionsExt;
use std::os::unix::io::AsRawFd;
use std::os::unix::io::RawFd;
use std::ptr;
use std::mem;
use std::ffi::OsStr;
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::symlink;
use std::os::unix::fs::FileTypeExt;
use std::os::unix::fs::OpenOptionsExt;
use std::os::unix::io::FromRawFd;
use std::os::unix::io::IntoRawFd;
use std::os::unix::fs::DirBuilder;
use std::os::unix::fs::DirEntry;
use std::os::unix::fs::FileType;
use std::os::unix::fs::Permissions;
use std::os::unix::fs::OpenOptions;
use std::os::unix::fs::MetadataExt;
use std::os::unix::fs::symlink_metadata;
use std::os::unix::fs::FileTimes;
use std::os::unix::fs::FileTimesExt;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt;
use std::os::unix::fs::DirBuilderExt;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::FileExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::unix::fs::OpenOptionsExt as _;
use std::os::unix::fs::FileTimesExt as _;
use std::os::unix::fs::FileTypeExt as _;
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::fs::MetadataExt as _;
use std::os::unix::fs::DirEntryExt as _;
use std::os::unix::fs::DirBuilderExt as _;
use std::os::un